import { Component } from '@angular/core';
import { User } from './models/user.model';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  btnDisabled = true;
  nombre: string = 'Henrry';
  edad: number = 26;
  imagen = 'https://source.unsplash.com/random';
  imagenwidth = 20;
  persona1 = {
    nombre: this.nombre,
    edad: this.edad,
    avatar: this.imagen,
    avatarTamano: this.imagenwidth,
  };

  personas2 = [
    {
      nombre: 'Henrry',
      edad: 25,
      avatar: 'https://source.unsplash.com/random',
      avatarTamano: this.imagenwidth,
    },
    {
      nombre: 'Leticia',
      edad: 26,
      avatar: 'https://source.unsplash.com/random',
      avatarTamano: this.imagenwidth,
    },
    {
      nombre: 'Jordy',
      edad: 2,
      avatar: 'https://source.unsplash.com/random',
      avatarTamano: this.imagenwidth,
    },
  ];
  users: User[] = [
    {
      id: '4a30e6a8-1124-4e96-a46d-714792833b3e',
      username: 'cmarshland0',
      imgePerfil: 'https://robohash.org/atquequinobis.png?size=50x50&set=set1',
      fullName: 'Clarissa Marshland',
      gender: 'Female',
      email: 'cmarshland0@japanpost.jp',
      age: 31,
      rol: 'Human Resources Assistant I',
      status: 'Activo',
    },
    {
      id: '6fd44439-1fa2-424c-bb51-64ba9fab337d',
      username: 'eambrosch1',
      imgePerfil:
        'https://robohash.org/aspernaturhicblanditiis.png?size=50x50&set=set1',
      fullName: 'Elroy Ambrosch',
      gender: 'Male',
      email: 'eambrosch1@noaa.gov',
      age: 73,
      rol: 'Dental Hygienist',
      status: 'Inactivo',
    },
    {
      id: '9a39bbab-f3e8-455c-b1ac-68e66788cdbe',
      username: 'kburstowe2',
      imgePerfil: 'https://robohash.org/quaseaquedicta.png?size=50x50&set=set1',
      fullName: 'Kaile Burstowe',
      gender: 'Female',
      email: 'kburstowe2@mail.ru',
      age: 77,
      rol: 'Administrative Officer',
      status: 'Activo',
    },
    {
      id: '89b7bae7-60a2-4208-988c-56fbc1fa8ac8',
      username: 'mmordin3',
      imgePerfil:
        'https://robohash.org/quiipsamdolorem.png?size=50x50&set=set1',
      fullName: 'Maurine Mordin',
      gender: 'Female',
      email: 'mmordin3@vinaora.com',
      age: 35,
      rol: 'Legal Assistant',
      status: 'Inactivo',
    },
    {
      id: '578cf04b-8986-4370-8906-859c383253bb',
      username: 'joscanlon4',
      imgePerfil:
        'https://robohash.org/blanditiisasperioreseum.png?size=50x50&set=set1',
      fullName: "Jeanelle O'Scanlon",
      gender: 'Female',
      email: 'joscanlon4@deliciousdays.com',
      age: 20,
      rol: 'Community Outreach Specialist',
      status: 'Espera',
    },
    {
      id: '9e4545a8-6927-42bb-b21e-5d42520e5c95',
      username: 'bbrisard5',
      imgePerfil:
        'https://robohash.org/hicofficiadebitis.png?size=50x50&set=set1',
      fullName: 'Bartolomeo Brisard',
      gender: 'Male',
      email: 'bbrisard5@zdnet.com',
      age: 69,
      rol: 'Cost Accountant',
      status: 'Inactivo',
    },
    {
      id: 'e7ff2103-a177-4d14-b139-11b49b571aa9',
      username: 'acullrford6',
      imgePerfil: 'https://robohash.org/utfacilisminus.png?size=50x50&set=set1',
      fullName: 'Arther Cullrford',
      gender: 'Male',
      email: 'acullrford6@newyorker.com',
      age: 26,
      rol: 'Geological Engineer',
      status: 'Espera',
    },
    {
      id: '7dd5c42c-a5d1-40f3-8189-e03f4cc20a8f',
      username: 'sbloodworthe7',
      imgePerfil:
        'https://robohash.org/delectusexcepturiet.png?size=50x50&set=set1',
      fullName: 'Shawna Bloodworthe',
      gender: 'Female',
      email: 'sbloodworthe7@netvibes.com',
      age: 74,
      rol: 'Media Manager I',
      status: 'Activo',
    },
    {
      id: '388714ce-16c9-491d-bac5-27c511c8c699',
      username: 'gravenhill8',
      imgePerfil: 'https://robohash.org/estmagnisint.png?size=50x50&set=set1',
      fullName: 'Gallard Ravenhill',
      gender: 'Male',
      email: 'gravenhill8@sbwire.com',
      age: 71,
      rol: 'Electrical Engineer',
      status: 'Activo',
    },
    {
      id: '5b797ce2-8fc2-46b4-b7bf-6c6e1dc73b06',
      username: 'bbartalucci9',
      imgePerfil: 'https://robohash.org/etsuntiste.png?size=50x50&set=set1',
      fullName: 'Berkie Bartalucci',
      gender: 'Male',
      email: 'bbartalucci9@pbs.org',
      age: 50,
      rol: 'Help Desk Operator',
      status: 'Espera',
    },
    {
      id: '48169b35-abc1-43e4-bf16-9de0ac822f84',
      username: 'kpearsea',
      imgePerfil:
        'https://robohash.org/etiustoasperiores.png?size=50x50&set=set1',
      fullName: 'Korry Pearse',
      gender: 'Female',
      email: 'kpearsea@jugem.jp',
      age: 61,
      rol: 'Recruiter',
      status: 'Espera',
    },
    {
      id: '99f4c055-f5a5-4205-bd5f-2007b0117285',
      username: 'tchampionb',
      imgePerfil:
        'https://robohash.org/dolorumquaerataccusamus.png?size=50x50&set=set1',
      fullName: 'Tiphanie Champion',
      gender: 'Female',
      email: 'tchampionb@yale.edu',
      age: 38,
      rol: 'Assistant Manager',
      status: 'Activo',
    },
    {
      id: 'a40465f2-7c8c-413e-b061-f5a2475e2b71',
      username: 'ctowardc',
      imgePerfil:
        'https://robohash.org/autsedperspiciatis.png?size=50x50&set=set1',
      fullName: 'Callida Toward',
      gender: 'Female',
      email: 'ctowardc@moonfruit.com',
      age: 65,
      rol: 'Director of Sales',
      status: 'Activo',
    },
    {
      id: 'a3bac804-7dab-47ae-ba40-2c18a9df1daa',
      username: 'bblackfordd',
      imgePerfil: 'https://robohash.org/oditodioquam.png?size=50x50&set=set1',
      fullName: 'Bud Blackford',
      gender: 'Male',
      email: 'bblackfordd@myspace.com',
      age: 71,
      rol: 'Geological Engineer',
      status: 'Inactivo',
    },
    {
      id: '6af5e59d-80ff-484c-a22d-06f5e286dcba',
      username: 'ctournaye',
      imgePerfil:
        'https://robohash.org/quisrationequos.png?size=50x50&set=set1',
      fullName: 'Corie Tournay',
      gender: 'Female',
      email: 'ctournaye@hibu.com',
      age: 18,
      rol: 'Environmental Specialist',
      status: 'Activo',
    },
    {
      id: '9fae7206-d350-437b-b02c-9207d16d5a13',
      username: 'lagglionef',
      imgePerfil:
        'https://robohash.org/ullamrationealiquid.png?size=50x50&set=set1',
      fullName: 'Lyon Agglione',
      gender: 'Male',
      email: 'lagglionef@hexun.com',
      age: 66,
      rol: 'Senior Editor',
      status: 'Activo',
    },
    {
      id: '7dc05b13-9138-4231-be2c-9fa0fe10756c',
      username: 'etatemg',
      imgePerfil:
        'https://robohash.org/dolorembeataeet.png?size=50x50&set=set1',
      fullName: 'Engelbert Tatem',
      gender: 'Male',
      email: 'etatemg@newyorker.com',
      age: 59,
      rol: 'Financial Analyst',
      status: 'Activo',
    },
    {
      id: 'd0f54211-6a88-499a-8a07-993c1d293ee7',
      username: 'sassandrih',
      imgePerfil:
        'https://robohash.org/occaecatiexpeditasimilique.png?size=50x50&set=set1',
      fullName: 'Sigismond Assandri',
      gender: 'Male',
      email: 'sassandrih@craigslist.org',
      age: 58,
      rol: 'Automation Specialist III',
      status: 'Espera',
    },
    {
      id: 'aa86606e-4f3d-48dc-94a7-8b5bc9c4da8b',
      username: 'lmilleai',
      imgePerfil:
        'https://robohash.org/sitducimusearum.png?size=50x50&set=set1',
      fullName: 'Lorant Millea',
      gender: 'Male',
      email: 'lmilleai@joomla.org',
      age: 25,
      rol: 'Recruiting Manager',
      status: 'Activo',
    },
    {
      id: '58f79cd4-f018-4d2d-bc12-0815f55a3337',
      username: 'slowlej',
      imgePerfil: 'https://robohash.org/earumeaqueeos.png?size=50x50&set=set1',
      fullName: 'Sallyanne Lowle',
      gender: 'Female',
      email: 'slowlej@a8.net',
      age: 61,
      rol: 'Clinical Specialist',
      status: 'Espera',
    },
    {
      id: 'd2d5f68d-dd58-426d-a08f-70bab3833de1',
      username: 'hcunneyk',
      imgePerfil:
        'https://robohash.org/reprehenderitminimaminus.png?size=50x50&set=set1',
      fullName: 'Hansiain Cunney',
      gender: 'Male',
      email: 'hcunneyk@va.gov',
      age: 59,
      rol: 'Accountant IV',
      status: 'Activo',
    },
    {
      id: '01e74b0a-bdd9-4aed-b98b-0540afdfa3b2',
      username: 'cquippl',
      imgePerfil:
        'https://robohash.org/nullaeligendiipsum.png?size=50x50&set=set1',
      fullName: 'Caesar Quipp',
      gender: 'Male',
      email: 'cquippl@nih.gov',
      age: 59,
      rol: 'Senior Quality Engineer',
      status: 'Inactivo',
    },
    {
      id: 'c4f24e00-4065-4eab-a32f-3b279cf011fb',
      username: 'cbinnionm',
      imgePerfil:
        'https://robohash.org/sedaspernaturconsequatur.png?size=50x50&set=set1',
      fullName: 'Ches Binnion',
      gender: 'Male',
      email: 'cbinnionm@ftc.gov',
      age: 48,
      rol: 'Help Desk Operator',
      status: 'Inactivo',
    },
    {
      id: '5158f4f4-b698-4f1f-a9f5-27bbe769e2bb',
      username: 'msterndalen',
      imgePerfil: 'https://robohash.org/sitadeum.png?size=50x50&set=set1',
      fullName: 'Maurizio Sterndale',
      gender: 'Male',
      email: 'msterndalen@columbia.edu',
      age: 31,
      rol: 'Senior Sales Associate',
      status: 'Espera',
    },
    {
      id: '02a6c40f-2698-4331-8d7f-c74b2edf8eb8',
      username: 'fguymero',
      imgePerfil: 'https://robohash.org/eteumid.png?size=50x50&set=set1',
      fullName: 'Farrell Guymer',
      gender: 'Male',
      email: 'fguymero@123-reg.co.uk',
      age: 52,
      rol: 'General Manager',
      status: 'Activo',
    },
    {
      id: '154ceeff-5c78-407d-b255-5f7ebc210cd6',
      username: 'schastneyp',
      imgePerfil:
        'https://robohash.org/consequaturaccusamuscumque.png?size=50x50&set=set1',
      fullName: 'Shandra Chastney',
      gender: 'Female',
      email: 'schastneyp@sakura.ne.jp',
      age: 76,
      rol: 'Director of Sales',
      status: 'Activo',
    },
    {
      id: '6d2225e2-fb41-449f-b236-d5b752a9dedf',
      username: 'smillsapq',
      imgePerfil: 'https://robohash.org/omnisquamdicta.png?size=50x50&set=set1',
      fullName: 'Sephira Millsap',
      gender: 'Female',
      email: 'smillsapq@zimbio.com',
      age: 66,
      rol: 'Tax Accountant',
      status: 'Espera',
    },
    {
      id: '79c9d44c-64d1-43f4-8e15-a39ec42a3679',
      username: 'mambrosinir',
      imgePerfil:
        'https://robohash.org/istenumquamsoluta.png?size=50x50&set=set1',
      fullName: 'Meredeth Ambrosini',
      gender: 'Male',
      email: 'mambrosinir@ameblo.jp',
      age: 64,
      rol: 'Tax Accountant',
      status: 'Activo',
    },
    {
      id: '8a7baa1a-630c-40ae-8352-2d3f4ee42487',
      username: 'wberrows',
      imgePerfil:
        'https://robohash.org/possimusvoluptasquod.png?size=50x50&set=set1',
      fullName: 'Wren Berrow',
      gender: 'Female',
      email: 'wberrows@oracle.com',
      age: 50,
      rol: 'Actuary',
      status: 'Inactivo',
    },
    {
      id: 'b1b7ca67-0f83-4928-8b52-03e93bd88132',
      username: 'rnanglet',
      imgePerfil: 'https://robohash.org/etquiaaut.png?size=50x50&set=set1',
      fullName: 'Robina Nangle',
      gender: 'Female',
      email: 'rnanglet@cam.ac.uk',
      age: 61,
      rol: 'Geologist I',
      status: 'Espera',
    },
    {
      id: '3cc18c47-9c06-442e-b58c-e1e1756441ac',
      username: 'cjuckesu',
      imgePerfil:
        'https://robohash.org/blanditiisnumquamnecessitatibus.png?size=50x50&set=set1',
      fullName: 'Corrina Juckes',
      gender: 'Female',
      email: 'cjuckesu@phpbb.com',
      age: 26,
      rol: 'Cost Accountant',
      status: 'Activo',
    },
    {
      id: 'da0ed7a6-0dca-46d3-808c-18f40dbd09fc',
      username: 'ajuarav',
      imgePerfil: 'https://robohash.org/harumlaboreet.png?size=50x50&set=set1',
      fullName: 'Anitra Juara',
      gender: 'Female',
      email: 'ajuarav@google.es',
      age: 73,
      rol: 'Actuary',
      status: 'Inactivo',
    },
    {
      id: '28fb6d32-74ae-4867-a26b-72cc345a54db',
      username: 'ccharlewoodw',
      imgePerfil: 'https://robohash.org/sedhicunde.png?size=50x50&set=set1',
      fullName: 'Cinda Charlewood',
      gender: 'Female',
      email: 'ccharlewoodw@weebly.com',
      age: 52,
      rol: 'Help Desk Operator',
      status: 'Espera',
    },
    {
      id: '4ddd79e4-0a02-4e77-8b8f-b6c4daa79fd2',
      username: 'rjaynex',
      imgePerfil: 'https://robohash.org/quoeaipsa.png?size=50x50&set=set1',
      fullName: 'Rorie Jayne',
      gender: 'Female',
      email: 'rjaynex@flavors.me',
      age: 69,
      rol: 'General Manager',
      status: 'Inactivo',
    },
    {
      id: '6de0f248-0e93-43ad-aa65-aa813bbaf485',
      username: 'lgeraudely',
      imgePerfil:
        'https://robohash.org/temporaeumconsequatur.png?size=50x50&set=set1',
      fullName: 'Lorry Geraudel',
      gender: 'Male',
      email: 'lgeraudely@naver.com',
      age: 26,
      rol: 'General Manager',
      status: 'Inactivo',
    },
    {
      id: '6e7a0699-ccb0-4849-9964-ed620f8c527a',
      username: 'mphinnessyz',
      imgePerfil:
        'https://robohash.org/culpaexcepturidignissimos.png?size=50x50&set=set1',
      fullName: 'Merrily Phinnessy',
      gender: 'Female',
      email: 'mphinnessyz@wufoo.com',
      age: 62,
      rol: 'Quality Engineer',
      status: 'Inactivo',
    },
    {
      id: '0cd4a03f-ad40-4ce4-93a7-0c249d3a371b',
      username: 'mcracoe10',
      imgePerfil:
        'https://robohash.org/minusearumsoluta.png?size=50x50&set=set1',
      fullName: 'Maible Cracoe',
      gender: 'Female',
      email: 'mcracoe10@ezinearticles.com',
      age: 77,
      rol: 'Help Desk Technician',
      status: 'Espera',
    },
    {
      id: '292fc568-1d80-46c7-b8ae-b62ae3e66d64',
      username: 'tscone11',
      imgePerfil: 'https://robohash.org/estsitet.png?size=50x50&set=set1',
      fullName: 'Tarah Scone',
      gender: 'Female',
      email: 'tscone11@theguardian.com',
      age: 62,
      rol: 'Biostatistician IV',
      status: 'Activo',
    },
    {
      id: '19567bff-6819-40e4-9322-f20ad391ff33',
      username: 'rdornin12',
      imgePerfil:
        'https://robohash.org/totamnihilearum.png?size=50x50&set=set1',
      fullName: 'Rodie Dornin',
      gender: 'Female',
      email: 'rdornin12@artisteer.com',
      age: 34,
      rol: 'VP Product Management',
      status: 'Activo',
    },
    {
      id: '11d579e1-c3dd-46d9-931a-6fc11934b144',
      username: 'cmcvitie13',
      imgePerfil:
        'https://robohash.org/consequaturquiatempora.png?size=50x50&set=set1',
      fullName: 'Cristionna McVitie',
      gender: 'Female',
      email: 'cmcvitie13@wordpress.com',
      age: 41,
      rol: 'Associate Professor',
      status: 'Espera',
    },
    {
      id: 'b488a98d-d1b4-4386-a2fe-6f0fbf079b55',
      username: 'dsymcoxe14',
      imgePerfil:
        'https://robohash.org/ullamquisquamdoloremque.png?size=50x50&set=set1',
      fullName: 'Danya Symcoxe',
      gender: 'Male',
      email: 'dsymcoxe14@time.com',
      age: 71,
      rol: 'Community Outreach Specialist',
      status: 'Activo',
    },
    {
      id: '1db52fa0-5fc1-4c01-8173-fd77b9d707a0',
      username: 'tcastro15',
      imgePerfil:
        'https://robohash.org/autliberodignissimos.png?size=50x50&set=set1',
      fullName: 'Tomaso Castro',
      gender: 'Male',
      email: 'tcastro15@ft.com',
      age: 27,
      rol: 'Senior Cost Accountant',
      status: 'Inactivo',
    },
    {
      id: '39441fa5-efa1-44b7-86f3-ae99a7f85706',
      username: 'kbarnhart16',
      imgePerfil: 'https://robohash.org/etetquod.png?size=50x50&set=set1',
      fullName: 'Karisa Barnhart',
      gender: 'Female',
      email: 'kbarnhart16@behance.net',
      age: 72,
      rol: 'Payment Adjustment Coordinator',
      status: 'Espera',
    },
    {
      id: '3eac14a7-b0b7-440b-a20c-78e33d90152a',
      username: 'kcardus17',
      imgePerfil: 'https://robohash.org/omnisaperiamid.png?size=50x50&set=set1',
      fullName: 'Karine Cardus',
      gender: 'Female',
      email: 'kcardus17@apple.com',
      age: 56,
      rol: 'Staff Scientist',
      status: 'Espera',
    },
    {
      id: '7d9734d3-a2a7-43c4-84f2-d2a1ae2b74a4',
      username: 'jrangeley18',
      imgePerfil:
        'https://robohash.org/inciduntfacilisea.png?size=50x50&set=set1',
      fullName: 'Jacobo Rangeley',
      gender: 'Male',
      email: 'jrangeley18@hao123.com',
      age: 61,
      rol: 'Marketing Assistant',
      status: 'Inactivo',
    },
    {
      id: '4572c995-81f8-49db-a785-56c0dd8fca0b',
      username: 'lgummie19',
      imgePerfil: 'https://robohash.org/eumettotam.png?size=50x50&set=set1',
      fullName: 'Lanette Gummie',
      gender: 'Female',
      email: 'lgummie19@ted.com',
      age: 25,
      rol: 'Food Chemist',
      status: 'Espera',
    },
    {
      id: 'e0a96fff-6db7-4119-8f53-278bd771366f',
      username: 'hcarman1a',
      imgePerfil:
        'https://robohash.org/odioconsequunturmollitia.png?size=50x50&set=set1',
      fullName: 'Herbie Carman',
      gender: 'Male',
      email: 'hcarman1a@youtube.com',
      age: 75,
      rol: 'Civil Engineer',
      status: 'Inactivo',
    },
    {
      id: '998c0818-8623-4241-ac70-fa42667e018b',
      username: 'fmattiello1b',
      imgePerfil:
        'https://robohash.org/officiaquiapariatur.png?size=50x50&set=set1',
      fullName: 'Forbes Mattiello',
      gender: 'Male',
      email: 'fmattiello1b@indiegogo.com',
      age: 19,
      rol: 'Quality Engineer',
      status: 'Espera',
    },
    {
      id: '780fae6c-e18b-44ad-964e-5c5eacab196c',
      username: 'frehme1c',
      imgePerfil:
        'https://robohash.org/sitmolestiaevoluptate.png?size=50x50&set=set1',
      fullName: 'Frederich Rehme',
      gender: 'Male',
      email: 'frehme1c@4shared.com',
      age: 18,
      rol: 'Programmer Analyst IV',
      status: 'Espera',
    },
    {
      id: 'cc39d0d0-52f8-44df-91be-5cdd1d1943f9',
      username: 'abellini1d',
      imgePerfil:
        'https://robohash.org/animivelitdolores.png?size=50x50&set=set1',
      fullName: 'Aeriel Bellini',
      gender: 'Female',
      email: 'abellini1d@msn.com',
      age: 21,
      rol: 'Senior Cost Accountant',
      status: 'Activo',
    },
    {
      id: '566385be-dc95-46c4-89b6-5eaf8815a50f',
      username: 'lmarchenko1e',
      imgePerfil:
        'https://robohash.org/rerumbeataeinventore.png?size=50x50&set=set1',
      fullName: 'Lannie Marchenko',
      gender: 'Male',
      email: 'lmarchenko1e@buzzfeed.com',
      age: 73,
      rol: 'Geologist II',
      status: 'Espera',
    },
    {
      id: '3546ece3-562f-44c1-8a7a-ca17bcb0b076',
      username: 'msmallcombe1f',
      imgePerfil:
        'https://robohash.org/animisimiliquequas.png?size=50x50&set=set1',
      fullName: 'Magdalene Smallcombe',
      gender: 'Female',
      email: 'msmallcombe1f@bloglines.com',
      age: 21,
      rol: 'Nuclear Power Engineer',
      status: 'Espera',
    },
    {
      id: '8af03942-ba07-4568-be04-ea6718f692b6',
      username: 'gsmitton1g',
      imgePerfil:
        'https://robohash.org/doloribusmaximesimilique.png?size=50x50&set=set1',
      fullName: 'Gabbie Smitton',
      gender: 'Female',
      email: 'gsmitton1g@vk.com',
      age: 79,
      rol: 'Sales Associate',
      status: 'Inactivo',
    },
    {
      id: '00892d07-df11-4b5e-8f86-30cef61e6d03',
      username: 'jparlett1h',
      imgePerfil: 'https://robohash.org/magnioditearum.png?size=50x50&set=set1',
      fullName: 'Jeralee Parlett',
      gender: 'Female',
      email: 'jparlett1h@baidu.com',
      age: 77,
      rol: 'Account Coordinator',
      status: 'Inactivo',
    },
    {
      id: '5112fb2f-3967-455e-a85d-ba0955192ba9',
      username: 'opiccop1i',
      imgePerfil:
        'https://robohash.org/enimreiciendisaliquam.png?size=50x50&set=set1',
      fullName: 'Orson Piccop',
      gender: 'Male',
      email: 'opiccop1i@ed.gov',
      age: 28,
      rol: 'Software Test Engineer II',
      status: 'Espera',
    },
    {
      id: '485e626c-7d9b-4d9d-abe1-551360bd1939',
      username: 'bportis1j',
      imgePerfil: 'https://robohash.org/quisolutahic.png?size=50x50&set=set1',
      fullName: 'Bendicty Portis',
      gender: 'Male',
      email: 'bportis1j@a8.net',
      age: 73,
      rol: 'Human Resources Manager',
      status: 'Inactivo',
    },
    {
      id: '832e3f09-7be0-443a-8a8c-fc3328b85777',
      username: 'ccodeman1k',
      imgePerfil: 'https://robohash.org/suntdolorsit.png?size=50x50&set=set1',
      fullName: 'Clevey Codeman',
      gender: 'Male',
      email: 'ccodeman1k@google.com.hk',
      age: 71,
      rol: 'Paralegal',
      status: 'Activo',
    },
    {
      id: '681a3b88-1d7c-4fd3-b3dd-afaed76ea40e',
      username: 'cpretley1l',
      imgePerfil:
        'https://robohash.org/cupiditateplaceatenim.png?size=50x50&set=set1',
      fullName: 'Carmita Pretley',
      gender: 'Female',
      email: 'cpretley1l@adobe.com',
      age: 19,
      rol: 'Legal Assistant',
      status: 'Inactivo',
    },
    {
      id: '6c16d38e-fbfc-437d-9823-12ec6edb5bc3',
      username: 'awinsiowiecki1m',
      imgePerfil:
        'https://robohash.org/nonquiarchitecto.png?size=50x50&set=set1',
      fullName: 'Anabelle Winsiowiecki',
      gender: 'Female',
      email: 'awinsiowiecki1m@nymag.com',
      age: 47,
      rol: 'Budget/Accounting Analyst II',
      status: 'Activo',
    },
    {
      id: '273577d6-3c03-4d3a-8ba3-1eb5519c0bf2',
      username: 'leddoes1n',
      imgePerfil: 'https://robohash.org/suntnobisenim.png?size=50x50&set=set1',
      fullName: 'Lea Eddoes',
      gender: 'Female',
      email: 'leddoes1n@privacy.gov.au',
      age: 36,
      rol: 'Accounting Assistant II',
      status: 'Inactivo',
    },
    {
      id: 'a32f27bf-edcb-4f9e-bdc7-993b1c1014e8',
      username: 'idungee1o',
      imgePerfil:
        'https://robohash.org/rerumdistinctiominus.png?size=50x50&set=set1',
      fullName: 'Innis Dungee',
      gender: 'Male',
      email: 'idungee1o@psu.edu',
      age: 65,
      rol: 'Actuary',
      status: 'Espera',
    },
    {
      id: 'a37c8704-4f96-45d8-9b54-532607130fcb',
      username: 'bdrakeley1p',
      imgePerfil:
        'https://robohash.org/officiisdoloreseligendi.png?size=50x50&set=set1',
      fullName: 'Blinnie Drakeley',
      gender: 'Female',
      email: 'bdrakeley1p@guardian.co.uk',
      age: 25,
      rol: 'Automation Specialist III',
      status: 'Activo',
    },
    {
      id: '3a530374-c013-4fbc-847d-a29e1364fba7',
      username: 'wpree1q',
      imgePerfil:
        'https://robohash.org/laboriosamdebitisvoluptatem.png?size=50x50&set=set1',
      fullName: 'Wiley Pree',
      gender: 'Male',
      email: 'wpree1q@zimbio.com',
      age: 40,
      rol: 'Senior Financial Analyst',
      status: 'Inactivo',
    },
    {
      id: 'df45115d-f7e5-421f-acfb-bf73faabcf55',
      username: 'atomczynski1r',
      imgePerfil:
        'https://robohash.org/perferendissitminima.png?size=50x50&set=set1',
      fullName: 'Ardeen Tomczynski',
      gender: 'Female',
      email: 'atomczynski1r@hexun.com',
      age: 65,
      rol: 'VP Accounting',
      status: 'Inactivo',
    },
    {
      id: 'c506fb83-1589-4d82-841e-a7d50e81f144',
      username: 'pabramovitch1s',
      imgePerfil: 'https://robohash.org/utsuscipiteum.png?size=50x50&set=set1',
      fullName: 'Parker Abramovitch',
      gender: 'Male',
      email: 'pabramovitch1s@illinois.edu',
      age: 49,
      rol: 'VP Marketing',
      status: 'Activo',
    },
    {
      id: '33944a1e-bdd7-4a15-a810-aed5a70af86e',
      username: 'hhumpage1t',
      imgePerfil:
        'https://robohash.org/dolorumdoloressed.png?size=50x50&set=set1',
      fullName: 'Hyatt Humpage',
      gender: 'Male',
      email: 'hhumpage1t@nyu.edu',
      age: 56,
      rol: 'Assistant Media Planner',
      status: 'Inactivo',
    },
    {
      id: '127066a6-2310-4001-a805-4c4e1eeb8ef1',
      username: 'ngrieveson1u',
      imgePerfil:
        'https://robohash.org/eatemporaarchitecto.png?size=50x50&set=set1',
      fullName: 'Nola Grieveson',
      gender: 'Female',
      email: 'ngrieveson1u@japanpost.jp',
      age: 63,
      rol: 'Compensation Analyst',
      status: 'Espera',
    },
    {
      id: 'f232734e-d769-4efa-8381-123768fed429',
      username: 'lwitherington1v',
      imgePerfil: 'https://robohash.org/adquoset.png?size=50x50&set=set1',
      fullName: 'Land Witherington',
      gender: 'Male',
      email: 'lwitherington1v@nytimes.com',
      age: 42,
      rol: 'VP Sales',
      status: 'Inactivo',
    },
    {
      id: '765daf54-b973-4ebc-bb48-4eb79b546e51',
      username: 'rlynnett1w',
      imgePerfil:
        'https://robohash.org/sapienteinciduntvel.png?size=50x50&set=set1',
      fullName: 'Rhonda Lynnett',
      gender: 'Female',
      email: 'rlynnett1w@latimes.com',
      age: 18,
      rol: 'Financial Advisor',
      status: 'Activo',
    },
    {
      id: 'eb0eede8-fa52-40ea-b774-dd84d8a55cfd',
      username: 'jvidgen1x',
      imgePerfil:
        'https://robohash.org/undeaccusamusexpedita.png?size=50x50&set=set1',
      fullName: 'Jean Vidgen',
      gender: 'Male',
      email: 'jvidgen1x@howstuffworks.com',
      age: 40,
      rol: 'Director of Sales',
      status: 'Inactivo',
    },
    {
      id: '12bfd998-213c-416f-be9b-2591a7964e3c',
      username: 'fbrownlow1y',
      imgePerfil:
        'https://robohash.org/magnamcupiditateunde.png?size=50x50&set=set1',
      fullName: 'Fancie Brownlow',
      gender: 'Female',
      email: 'fbrownlow1y@fastcompany.com',
      age: 48,
      rol: 'Budget/Accounting Analyst II',
      status: 'Espera',
    },
    {
      id: '5ba27249-cc32-46cf-b589-a7a55774e12d',
      username: 'rpozzo1z',
      imgePerfil:
        'https://robohash.org/praesentiumvelitmagni.png?size=50x50&set=set1',
      fullName: 'Rinaldo Pozzo',
      gender: 'Male',
      email: 'rpozzo1z@nps.gov',
      age: 60,
      rol: 'Operator',
      status: 'Espera',
    },
    {
      id: '34ac5c61-6184-49c2-8e5e-3a6082a9293a',
      username: 'pjacobsohn20',
      imgePerfil:
        'https://robohash.org/occaecaticumharum.png?size=50x50&set=set1',
      fullName: 'Pat Jacobsohn',
      gender: 'Female',
      email: 'pjacobsohn20@wisc.edu',
      age: 54,
      rol: 'Software Test Engineer II',
      status: 'Activo',
    },
    {
      id: '7aafef90-6b07-4e57-bb26-c778bbdf4272',
      username: 'lscarse21',
      imgePerfil: 'https://robohash.org/siteligendicum.png?size=50x50&set=set1',
      fullName: 'Loren Scarse',
      gender: 'Female',
      email: 'lscarse21@ask.com',
      age: 45,
      rol: 'Social Worker',
      status: 'Inactivo',
    },
    {
      id: '02c065c3-c12b-41e2-84b2-09b30cafe1fa',
      username: 'hlinggard22',
      imgePerfil: 'https://robohash.org/adodioeius.png?size=50x50&set=set1',
      fullName: 'Harlan Linggard',
      gender: 'Male',
      email: 'hlinggard22@unc.edu',
      age: 47,
      rol: 'Help Desk Operator',
      status: 'Activo',
    },
    {
      id: '9e15fea5-c395-4e97-b355-180c209e41ca',
      username: 'jmccorkindale23',
      imgePerfil: 'https://robohash.org/sintnemoid.png?size=50x50&set=set1',
      fullName: 'Jerrilyn McCorkindale',
      gender: 'Female',
      email: 'jmccorkindale23@sina.com.cn',
      age: 70,
      rol: 'Help Desk Technician',
      status: 'Inactivo',
    },
    {
      id: 'f56f4e5d-2076-4b53-baac-f671e634699b',
      username: 'dchapelle24',
      imgePerfil:
        'https://robohash.org/minimadeseruntodio.png?size=50x50&set=set1',
      fullName: 'Donna Chapelle',
      gender: 'Female',
      email: 'dchapelle24@hud.gov',
      age: 38,
      rol: 'Design Engineer',
      status: 'Activo',
    },
    {
      id: 'adb7910a-3870-4483-ba73-dd79302a11cb',
      username: 'jfinn25',
      imgePerfil: 'https://robohash.org/minusquiaillum.png?size=50x50&set=set1',
      fullName: 'Joya Finn',
      gender: 'Female',
      email: 'jfinn25@ehow.com',
      age: 76,
      rol: 'Chief Design Engineer',
      status: 'Activo',
    },
    {
      id: 'f0390743-db6a-4c24-b9f5-ee9d199f73ea',
      username: 'gwrought26',
      imgePerfil: 'https://robohash.org/quietsimilique.png?size=50x50&set=set1',
      fullName: 'Gilda Wrought',
      gender: 'Female',
      email: 'gwrought26@bloglines.com',
      age: 67,
      rol: 'Food Chemist',
      status: 'Espera',
    },
    {
      id: 'e86d7df5-784a-4621-8269-ac58b89ebb28',
      username: 'lfrearson27',
      imgePerfil:
        'https://robohash.org/temporeestomnis.png?size=50x50&set=set1',
      fullName: 'Lorrie Frearson',
      gender: 'Male',
      email: 'lfrearson27@irs.gov',
      age: 38,
      rol: 'Cost Accountant',
      status: 'Inactivo',
    },
    {
      id: 'db68839c-b803-4bc3-87c3-28d28f1093b9',
      username: 'rvakhrushev28',
      imgePerfil:
        'https://robohash.org/rerumvoluptatumenim.png?size=50x50&set=set1',
      fullName: 'Rob Vakhrushev',
      gender: 'Male',
      email: 'rvakhrushev28@huffingtonpost.com',
      age: 65,
      rol: 'Senior Developer',
      status: 'Activo',
    },
    {
      id: 'cbf41cef-328a-49e0-b94b-0eb072ece464',
      username: 'hitchingham29',
      imgePerfil:
        'https://robohash.org/liberositcorporis.png?size=50x50&set=set1',
      fullName: 'Hermine Itchingham',
      gender: 'Female',
      email: 'hitchingham29@state.gov',
      age: 77,
      rol: 'Biostatistician III',
      status: 'Espera',
    },
    {
      id: '0df470ed-c0e5-484f-b441-d8b8467bdb40',
      username: 'tgilffillan2a',
      imgePerfil: 'https://robohash.org/autautquod.png?size=50x50&set=set1',
      fullName: 'Trenna Gilffillan',
      gender: 'Female',
      email: 'tgilffillan2a@ox.ac.uk',
      age: 73,
      rol: 'GIS Technical Architect',
      status: 'Activo',
    },
    {
      id: '5bf7291d-eeed-44c4-8b3b-ab3fe9c4c7cb',
      username: 'ceddleston2b',
      imgePerfil: 'https://robohash.org/nullaetveniam.png?size=50x50&set=set1',
      fullName: 'Cazzie Eddleston',
      gender: 'Male',
      email: 'ceddleston2b@arstechnica.com',
      age: 73,
      rol: 'Human Resources Manager',
      status: 'Activo',
    },
    {
      id: '60ed6dad-6ff0-432e-abc3-4f56eb152573',
      username: 'emartynikhin2c',
      imgePerfil:
        'https://robohash.org/quiasperioresreiciendis.png?size=50x50&set=set1',
      fullName: 'Ellerey Martynikhin',
      gender: 'Male',
      email: 'emartynikhin2c@flavors.me',
      age: 37,
      rol: 'Librarian',
      status: 'Espera',
    },
    {
      id: '526946ef-485a-4d12-8e58-6127c09ec7da',
      username: 'cover2d',
      imgePerfil:
        'https://robohash.org/ipsumveniamlabore.png?size=50x50&set=set1',
      fullName: 'Carla Over',
      gender: 'Female',
      email: 'cover2d@who.int',
      age: 39,
      rol: 'Design Engineer',
      status: 'Espera',
    },
    {
      id: '4774cf2d-48ca-44ab-8784-ba73358cb94a',
      username: 'tsartin2e',
      imgePerfil: 'https://robohash.org/sintomnisut.png?size=50x50&set=set1',
      fullName: 'Tim Sartin',
      gender: 'Female',
      email: 'tsartin2e@liveinternet.ru',
      age: 34,
      rol: 'Professor',
      status: 'Espera',
    },
    {
      id: '0e2c7ccc-1247-43bb-8139-0a5a9715e28c',
      username: 'cburless2f',
      imgePerfil:
        'https://robohash.org/delenitiperferendisrecusandae.png?size=50x50&set=set1',
      fullName: 'Cthrine Burless',
      gender: 'Female',
      email: 'cburless2f@amazon.co.jp',
      age: 33,
      rol: 'Database Administrator IV',
      status: 'Espera',
    },
    {
      id: '68fb0601-27b0-4271-92e2-bf7e6a2e8b3d',
      username: 'htimbridge2g',
      imgePerfil:
        'https://robohash.org/delectusperferendisa.png?size=50x50&set=set1',
      fullName: 'Hall Timbridge',
      gender: 'Male',
      email: 'htimbridge2g@cornell.edu',
      age: 24,
      rol: 'Senior Sales Associate',
      status: 'Activo',
    },
    {
      id: '99c4257e-be8b-43b7-a735-5cc3d7d2eba9',
      username: 'cwinridge2h',
      imgePerfil: 'https://robohash.org/quasicumea.png?size=50x50&set=set1',
      fullName: 'Carlo Winridge',
      gender: 'Male',
      email: 'cwinridge2h@apache.org',
      age: 33,
      rol: 'Analyst Programmer',
      status: 'Activo',
    },
    {
      id: 'cf6a3c7d-2d81-4f85-b384-c74942cb1cad',
      username: 'bmehmet2i',
      imgePerfil: 'https://robohash.org/modieligendia.png?size=50x50&set=set1',
      fullName: 'Bel Mehmet',
      gender: 'Female',
      email: 'bmehmet2i@house.gov',
      age: 35,
      rol: 'Legal Assistant',
      status: 'Espera',
    },
    {
      id: '89a2ff94-78b0-41a7-be5f-1938ff463768',
      username: 'jhullin2j',
      imgePerfil:
        'https://robohash.org/officiaestomnis.png?size=50x50&set=set1',
      fullName: 'Jerrold Hullin',
      gender: 'Male',
      email: 'jhullin2j@newsvine.com',
      age: 78,
      rol: 'Automation Specialist II',
      status: 'Inactivo',
    },
    {
      id: '7860df40-7411-4237-b334-cf161825adaa',
      username: 'ldjekic2k',
      imgePerfil:
        'https://robohash.org/molestiaererumet.png?size=50x50&set=set1',
      fullName: 'Lewie Djekic',
      gender: 'Male',
      email: 'ldjekic2k@lycos.com',
      age: 55,
      rol: 'Biostatistician II',
      status: 'Activo',
    },
    {
      id: 'd77cd41c-9c69-4506-9e37-d33f3f1126b8',
      username: 'bgeoghegan2l',
      imgePerfil:
        'https://robohash.org/utperspiciatisdebitis.png?size=50x50&set=set1',
      fullName: 'Berkeley Geoghegan',
      gender: 'Male',
      email: 'bgeoghegan2l@123-reg.co.uk',
      age: 76,
      rol: 'Marketing Assistant',
      status: 'Activo',
    },
    {
      id: 'fffe6ef2-f13d-47f6-b091-10294511aac5',
      username: 'dbedward2m',
      imgePerfil: 'https://robohash.org/impeditvelitet.png?size=50x50&set=set1',
      fullName: 'Doug Bedward',
      gender: 'Male',
      email: 'dbedward2m@auda.org.au',
      age: 44,
      rol: 'Engineer II',
      status: 'Espera',
    },
    {
      id: '849f5726-c271-4332-8412-11d583c32987',
      username: 'abrunsden2n',
      imgePerfil:
        'https://robohash.org/etnostrumvoluptates.png?size=50x50&set=set1',
      fullName: 'Alejandrina Brunsden',
      gender: 'Female',
      email: 'abrunsden2n@house.gov',
      age: 67,
      rol: 'Environmental Tech',
      status: 'Activo',
    },
    {
      id: '115270b3-4a70-4f02-bca4-e3e8ad776e34',
      username: 'hwiddicombe2o',
      imgePerfil:
        'https://robohash.org/veniammolestiasasperiores.png?size=50x50&set=set1',
      fullName: 'Hollie Widdicombe',
      gender: 'Female',
      email: 'hwiddicombe2o@java.com',
      age: 51,
      rol: 'Nurse',
      status: 'Espera',
    },
    {
      id: '1151fc85-1f68-45d4-ab8f-284f62808532',
      username: 'aswetmore2p',
      imgePerfil:
        'https://robohash.org/doloremimpeditfugiat.png?size=50x50&set=set1',
      fullName: 'Allie Swetmore',
      gender: 'Female',
      email: 'aswetmore2p@loc.gov',
      age: 38,
      rol: 'Assistant Professor',
      status: 'Activo',
    },
    {
      id: '51a93575-32d1-4d7b-82e9-83f199d88f2d',
      username: 'ckubicka2q',
      imgePerfil:
        'https://robohash.org/officiatemporibusmodi.png?size=50x50&set=set1',
      fullName: 'Christyna Kubicka',
      gender: 'Female',
      email: 'ckubicka2q@blogs.com',
      age: 60,
      rol: 'VP Product Management',
      status: 'Inactivo',
    },
    {
      id: 'ecbecef1-0db8-401e-8e28-5a9fb000773e',
      username: 'lcoopman2r',
      imgePerfil:
        'https://robohash.org/ipsavoluptateperferendis.png?size=50x50&set=set1',
      fullName: 'Lucas Coopman',
      gender: 'Male',
      email: 'lcoopman2r@webnode.com',
      age: 55,
      rol: 'Payment Adjustment Coordinator',
      status: 'Inactivo',
    },
  ];

  toggleButton() {
    this.btnDisabled = !this.btnDisabled;
  }
  aumentarEdad() {
    this.persona1.edad++;
  }

  aumentarImagen() {
    this.imagenwidth = this.imagenwidth * 2;
  }

  onScroll(event: Event) {
    const element = event.target as HTMLElement;
    console.log(element.scrollTop);
  }

  cambiNombre(event: Event) {
    const element = event.target as HTMLInputElement;
    this.persona1.nombre = element.value;
  }

  addPerson() {
    let persona2 = {
      nombre: this.nombre,
      edad: this.edad,
      avatar: this.imagen,
      avatarTamano: this.imagenwidth,
    };

    this.personas2.push(persona2);
    this.nombre = '';
    this.edad = 0;
  }

  deletePerson(index: number) {
    this.personas2.splice(index, 1);
  }
}
